default: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:
  api_host: localhost
  api_port: 443
  ssl_verify: false
  secret: ""
  # token needs to be populated before start up
  token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  namespace: argo
  workflow_base_dir: "/opt/dev/atmosphere-argo/"

  zoneinfo: "/usr/share/zoneinfo/US/Arizona"
  callback_url: "https://localhost/callback"
  callback_token: "bbbbbbbbbbbbbbbbbbbbbbbbbb"
